version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.7


    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - api-dependencies-{{ checksum "toolset-api/package.json" }}
            - api-dependencies-
            
      - run: cd toolset-api && npm install
      
      - save_cache:
          paths:
            - toolset-api/node_modules
          key: api-dependencies-{{ checksum "toolset-api/package.json" }}

      - run: cd toolset-api && npm test