version: 2
jobs:
  api_test:
    docker:
      - image: circleci/node:11.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "hello world"


workflows:
  version: 2
  unit_test:
    jobs:
      - api_test


