version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.7-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - api-dependencies-{{ checksum "toolset-api/package.json" }}
            - api-dependencies-

      - run: 
          name: Installing API dependencies
          command: cd toolset-api && npm install
      
      - save_cache:
          paths:
            - toolset-api/node_modules
          key: api-dependencies-{{ checksum "toolset-api/package.json" }}

      - run:
          name: Running API unit tests
          command: cd toolset-api && npm run coverage

      - store_artifacts:
          path: toolset-api/coverage

      - restore_cache:
          keys:
            - react-dependencies-{{ checksum "toolset-react/package.json" }}
            - react-dependencies-

      - run: 
          name: Installing React dependencies
          command: cd toolset-react && npm install
      
      - save_cache:
          paths:
            - toolset-react/node_modules
          key: react-dependencies-{{ checksum "toolset-react/package.json" }}

      - run: 
          name: Running React unit tests
          command: cd toolset-react && npm run coverage

      - store_artifacts:
          path: toolset-react/coverage

      - restore_cache:
          keys:
            - angular-dependencies-{{ checksum "toolset-angular/package.json" }}
            - angular-dependencies-

      - run: 
          name: Installing Angular dependencies
          command: cd toolset-angular && npm install
      
      - save_cache:
          paths:
            - toolset-angular/node_modules
          key: angular-dependencies-{{ checksum "toolset-angular/package.json" }}

      - run: 
          name: Running Angular unit tests
          command: cd toolset-angular && npm run coverage

      - store_artifacts:
          path: toolset-angular/coverage


